services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DATABASE_URL=file:/data/dev.db
    ports:
      - "5001:5001"
    volumes:
      - dbdata:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5001/api/health"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  frontend:
    image: uw_pico_509-frontend:latest
    environment:
      - VITE_API_URL=http://backend:5001
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  dbdata:
