services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DATABASE_URL=file:/data/dev.db
    ports:
      - "5001:5001"
    volumes:
      - dbdata:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5001/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  dbdata:
